// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBSaBFhB5OGrXAJhbv-rEiMvjCJPNWuI8',
    appId: '1:60051431375:web:d4c30e5d7fbdc86a12bcba',
    messagingSenderId: '60051431375',
    projectId: 'homework4-d4a72',
    authDomain: 'homework4-d4a72.firebaseapp.com',
    storageBucket: 'homework4-d4a72.appspot.com',
    measurementId: 'G-WEFQ393RMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWkzG0ye50piaB3UFyc3JBZ1r1Z3rS4Ps',
    appId: '1:60051431375:android:9bce38e5a713a5b812bcba',
    messagingSenderId: '60051431375',
    projectId: 'homework4-d4a72',
    storageBucket: 'homework4-d4a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqLWKbmI70hjhI63RifCvGlXgxyUO9PQ',
    appId: '1:60051431375:ios:7b979e5f30a32b8912bcba',
    messagingSenderId: '60051431375',
    projectId: 'homework4-d4a72',
    storageBucket: 'homework4-d4a72.appspot.com',
    iosBundleId: 'com.example.messageboardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArqLWKbmI70hjhI63RifCvGlXgxyUO9PQ',
    appId: '1:60051431375:ios:4190b0bc57222a9412bcba',
    messagingSenderId: '60051431375',
    projectId: 'homework4-d4a72',
    storageBucket: 'homework4-d4a72.appspot.com',
    iosBundleId: 'com.example.messageboardapp.RunnerTests',
  );
}
